[package]
name = "paimon"
version = "0.1.0"
authors = ["MeiK <meik2333@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.1.16"
libc = "0.2"

[lib]
name = "paimon"
crate-type = ["dylib"]
